### ISSUE TITLE
Log-In/Sign Up

### ISSUE THREAD

**Issue by eric-cc-su** [eric-cc-su/K9_Innoservice#13]
Create Log-In/Sign Up page to welcome users.

**Log In Page Requirements:**
-Username field
-Password field
-"Forgot Password?" link

**Sign Up Page Requirements:**
-Name
-Email
-Username
-password
-confirm password
-Dietary Restrictions

**Comment by eric-cc-su** [comment]
After Login, offer Profile page

**Comment by vkaran101** [comment]
![img_0699 3](https://cloud.githubusercontent.com/assets/10577587/6138209/324a57ec-b14d-11e4-893f-20fcdfa167ca.JPG)

**Comment by eric-cc-su** [comment]
Pull #30 includes commits 9a0b804b6835c35e09ea7ae161a76099a0efa486 (Sign Up Page) and 31a42673b4a24beff6167a2da17f4eb5f6fed500 (Log In dialogue) as proposed

**Comment by eric-cc-su** [comment]
**Sign Up page with log-in dialogue open**
![k9_signup_open](https://cloud.githubusercontent.com/assets/9936937/6183607/da7d24d4-b324-11e4-94b5-fdf523d397d6.png)
