### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by eric-cc-su** [eric-cc-su/K9_Innoservice#14]
Showcase features of site and how they work, also include:
-FAQs
-Typical help issues

**Comment by vkaran101** [comment]
![img_0698](https://cloud.githubusercontent.com/assets/10577587/6138155/e07e09b8-b14c-11e4-985a-fde696dd6d1d.JPG)

**Comment by eric-cc-su** [comment]
Commit a4bbdec7fdbd5e094d375c711e161b32efd3110d introduces Support page as proposed

![image](https://cloud.githubusercontent.com/assets/9936937/6141862/ce1a854e-b179-11e4-9775-3e5fa9555c3a.png)
