### ISSUE TITLE
Home Page layout proposal

### ISSUE THREAD

**Issue by eric-cc-su** [eric-cc-su/K9_Innoservice#17]
Background images that transition on timer. Scrolling = background is static, tiles move.

Color scheme: http://www.colourlovers.com/palette/3577248/

**Comment by farrahchow** [comment]
http://i.imgur.com/XQu0uHB.png
:)

**Comment by farrahchow** [comment]
http://i.imgur.com/ia4RWft.png the mascot!

**Comment by eric-cc-su** [comment]
4a5b0e62605dcb0791fd16431578b09fed5f330a Home Page Commit implements left-side sidebar for friend feed in proposal:
![k9_home_left_feed_closed](https://cloud.githubusercontent.com/assets/9936937/5931750/d037e17e-a66f-11e4-8fe0-3e75bef1f05d.png)
![k9_home_left_feed_open](https://cloud.githubusercontent.com/assets/9936937/5931751/d03bd054-a66f-11e4-8e71-f630a0d3a1de.png)

**Comment by eric-cc-su** [comment]
http://i.imgur.com/59AbCJp.png

**Comment by eric-cc-su** [comment]
Merge #24 includes completed home page
