### ISSUE TITLE
Featured Recipes Page

### ISSUE THREAD

**Issue by eric-cc-su** [eric-cc-su/K9_Innoservice#20]
Contains Trending/featured people and recipes. Completely detailed "feed" with what's popular in "article" format.

**Comment by tsaobaobao** [comment]
Overall layout:
![img_9105](https://cloud.githubusercontent.com/assets/10541755/6092745/0ed3eaca-aea1-11e4-934f-0873e0885104.JPG)

Detailed description of each square (left):
![img_9104](https://cloud.githubusercontent.com/assets/10541755/6092746/11899b34-aea1-11e4-9ad2-79b999d7f559.JPG)

**Comment by eric-cc-su** [comment]
**New Tile Design**
![img_2279](https://cloud.githubusercontent.com/assets/9936937/6136388/56ce7a30-b13e-11e4-99ac-feef779cf3ba.JPG)

**Comment by eric-cc-su** [comment]
http://gyazo.com/95cf40e85a1adab0c872551ddb98155c

**Comment by eric-cc-su** [comment]
Featured (like large blog post, not feed):
Most viewed recipe: overall of month, dessert/entree/appetizer/snack of month
Most liked recipe: overall of month, dessert/entree/appetizer/snack of month
Most commented

**Comment by eric-cc-su** [comment]
commit be2812b264ba2a6daa872de53298a7f58dff7f67 features first draft of page as proposed
