### ISSUE TITLE
Feed Page

### ISSUE THREAD

**Issue by eric-cc-su** [eric-cc-su/K9_Innoservice#21]
Everything that is current that friends are up to (Timeline vs Trending, this is the timeline)

**Comment by tsaobaobao** [comment]
Overall layout:
![img_9105](https://cloud.githubusercontent.com/assets/10541755/6092745/0ed3eaca-aea1-11e4-934f-0873e0885104.JPG)

Detailed description of each square (left):
![img_9104](https://cloud.githubusercontent.com/assets/10541755/6092746/11899b34-aea1-11e4-9ad2-79b999d7f559.JPG)

**Comment by eric-cc-su** [comment]
Commit 1d4a794ec9705142f4434063a014a2751de15857 introduces Feed/All Recipes page
![k9_all_recipes](https://cloud.githubusercontent.com/assets/9936937/6183500/f3930fac-b323-11e4-8a01-f244206c3bf1.png)
