### ISSUE TITLE
Update Profile Page

### ISSUE THREAD

**Issue by eric-cc-su** [eric-cc-su/K9_Innoservice#34]
Updated user's "self" profile page to include social media interactions. @farrahchow @dangster

**Comment by farrahchow** [comment]
http://i.gyazo.com/12adde5a127af840a0157801c92daf07.png

**Comment by eric-cc-su** [comment]
![img_2310](https://cloud.githubusercontent.com/assets/9936937/6590363/fda0cf1e-c784-11e4-9752-664f3c69dd65.JPG)

**Comment by eric-cc-su** [comment]
@dangster (Khoi) and @vkaran101 (Vandana) decide additional content needed in profile page (Consider whether content feed needs to be included: issue #53), @farrahchow (Farrah) and @tsaobaobao (Lynn) design new layout once Khoi & Vandana's decision confirmed

**Comment by tsaobaobao** [comment]
![11132038_1057199517629111_728455946_n](https://cloud.githubusercontent.com/assets/10541755/6952348/4a9a9ece-d88f-11e4-9706-8e3ae5ba32c9.jpg)

Sorry for my bad hand writing T_T

Healthy Husky in top left corner
Next to is says "Picture of fav dish, ingredients, or any other foody pic)

Right of user pic = buttons for following, sending a message, and blocking
Below user pic = username, # of followers, dietary restrictions (optional), and short description/message from user (optional)

Right side
Username's Recipes
<3 Recipes
Following (these users)
***Under each of these is a list of pics with a recipe title/username
By using either a scroll bar or clicking on a right arrow, you can look through the list of pics
