### ISSUE TITLE
Design/Re-design dedicated Feed Area (sidebar) for users

### ISSUE THREAD

**Issue by eric-cc-su** [eric-cc-su/K9_Innoservice#53]
The feed page should be dedicated to the logged in user's friends/community activity.
Items on Feed should include new recipes, user/friend comments on recipes, user/friend communication to eachother, etc.. (similar to Facebook wall, Tumblr feed, Pinterest wall)

Consider whether feed should be integrated into the profile page as main focal point, stay separate (Tumblr), or both (Facebook).

@dangster (Khoi) on lead for types of feed posts and content included in each post, @tsaobaobao and @farrahchow on aesthetics

**Comment by dangster** [comment]
![img_1360](https://cloud.githubusercontent.com/assets/10577584/6876550/e0c85174-d49e-11e4-9ffd-18451dd88b7f.JPG)

**Comment by dangster** [comment]
on the picture we can just have the users their following or friends with and what they've posted or liked
Have the user name and small profile picture and then a modified tile of what they uploaded or liked

**Comment by eric-cc-su** [comment]
Commit a1ce5499d62ef885565d2897c7f442b79e9d4676 introduces this feature, should be polished

**Comment by eric-cc-su** [comment]
Commit a91d8eb55032a8382a3bc824e1c4c95f8e569b40 introduces fully-designed side-feed
